name: Docker Pull Release

on:
  pull_request:
    branches: [nightly]
    types: [closed]

jobs:
  increment-version:
    runs-on: ubuntu-latest
    if: github.base_ref == 'nightly' && github.event.pull_request.merged
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: nightly
          fetch-depth: 0

      - name: Update VERSION
        id: update-version
        run: |
            value=$(cat VERSION)
            old_msg=$(git log -1 HEAD --pretty=format:%s)
          
            if [[ "$value" == *"-"* ]]; then
                build_value="$((${value#*-build} + 1))"
                new_value="${value%-build*}-build${build_value}"
                new_msg="[${build_value}] ${old_msg}"
            elif [[ "$value" == *"!"* ]]; then
                new_value="${value%!*}"
                new_msg="[${new_value}] ${old_msg}"
            else
                new_value="${value%-build*}-build1"
                new_msg="[1] ${old_msg}"
            fi
          
            echo "commit-msg=${new_msg}" >> $GITHUB_OUTPUT
            echo "commit-hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
            echo "commit-short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            
            echo "$new_value" > "VERSION"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add VERSION
            git commit -m "${new_msg}" --amend
            git push origin nightly --force-with-lease

      - name: Commit Info
        run: |
          echo "[${{ steps.update-version.outputs.commit-short }}](https://github.com/Kometa-Team/Kometa/commit/${{ steps.update-version.outputs.commit-hash }}) ${{ steps.update-version.outputs.commit-msg }}"

      - name: Branch Info
        run: |
          echo "${{ github.head_ref }}"
