name: Labeled

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:

  validate-pull:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'tester' # github.event.action == 'labeled' &&
    steps:

      - name: Display Refs
        id: refs
        run: |
          echo "Base Repo: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Body 1: ${{ github.event.pull_request.body }}"
          
          #body="${{ github.event.pull_request.body }}"
          #echo "Body 2: $body"
          #body=${body#*$## Description$'\n'}
          #echo "Body 3: $body"
          #body=${body%%$'\n'## Issues Fixed or Closed*}
          
          body=$(echo "${{ github.event.pull_request.body }}" | perl -0777 -ne '/.*## Description(.*)##.*/ && print $1,"\n"; ')
          #-n '/## Description/,/## Issues Fixed or Closed/{/## Description/b;/## Issues Fixed or Closed/b;p}'
          echo "Body 4: $body"
          body=${body//[[:space:]]/}
          echo "Body 5: $body"
          echo "description=$body" >> $GITHUB_OUTPUT
          

      - name: Discord Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          message: "Tester"
          title: ${{ github.event.pull_request.title }}
          description: ${{ steps.refs.outputs.description }}
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/pull/${{ github.event.number }}
          color: ${{ vars.COLOR_SUCCESS }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.GIT_NAME }}
          author_icon_url: ${{ vars.GIT_IMAGE }}