name: Labeled

on:
  pull_request:
    types: [labeled]

jobs:

  validate-pull:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'tester')
    steps:

      - name: Display Refs
        run: |
          echo "Base Repo: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head Ref: ${{ github.head_ref }}"