name: Nightly Build

on:
  workflow_run:
    workflows: ["Release New Version"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Commit Info
        run: |
          echo "TEST"
