name: Release New Version

on:
  workflow_dispatch:

jobs:
  ff-master:
    runs-on: ubuntu-latest
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: nightly
          fetch-depth: 0

      - name: Fast Forward Master
        run: |
            value=$(cat VERSION)
            version="${value%-build*}"
            echo "CURRENT_VERSION: '${version}'"
          
            MAJOR=$(awk -F. '{print $1}' <<< ${VER})
            MINOR=$(awk -F. '{print $2}' <<< ${VER})
            PATCH=$(awk -F. '{print $3}' <<< ${VER})
            PATCH=$((PATCH+1))
          
            echo "MAJOR='${MAJOR}'"
            echo "MINOR='${MINOR}'"
            echo "PATCH='${PATCH}'"
            echo "NEWVERSION='${MAJOR}.${MINOR}.${PATCH}'"
          
            echo "${MAJOR}.${MINOR}.${PATCH}" > "VERSION"
          
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add VERSION
            git commit -m "Kometa Release ${next_version}"
            git push origin nightly
            git push origin refs/heads/nightly:refs/heads/develop
            git push origin refs/heads/nightly:refs/heads/main
