name: Tag

on:
  push:
    branches: [ main ]

jobs:

  tag-new-versions:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 2

      - uses: Kometa-Team/tag-new-version@master
        with:
          tag-annotation-template: ""
          version-command: |
            cat VERSION
