name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check main
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from develop. ${{ github.base_ref }} ${{ github.head_ref }}"
          exit 1
      - name: Check develop
        if: github.base_ref == 'develop' && github.head_ref != 'nightly'
        run: |
          echo "ERROR: You can only merge to develop from nightly. ${{ github.base_ref }} ${{ github.head_ref }}"
          exit 1