name: 'Remove Tag'

on:
  workflow_dispatch:

jobs:
  remove-tag:
    runs-on: ubuntu-latest
    steps:
      - name: remove tag
        run: |
            HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKER_HUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKER_HUB_PASSWORD }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
            curl -i -X DELETE \
            -H "Accept: application/json" \
            -H "Authorization: JWT $HUB_TOKEN" \
            https://hub.docker.com/v2/repositories/kometateam/kometa/tags/letterboxd-user-lists/