name: TEST

on:
  push:
    branches: [ master, main ]

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.verify_diff.outputs.changed }}
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changes
        id: changed-files
        run: echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT

      - name: List changed files
        id: verify_diff
        run: |
            for file in ${{ steps.changed-files.outputs.changed_files }}; do
                if [[ $file == defaults/* ]] || [[ $file == modules/* ]] || [[ $file == main.py ]] ; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                fi
            done
  

  docker:
    needs: changes
    if: ${{ needs.changes.outputs.changed }} == 'true'
    runs-on: ubuntu-latest
    steps:

      - name: Discord Failure Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          title: "TRUE"
          color: 14879811
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/bot.png
          author: GitHub
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/git.png
